import Script from "next/script";

export const metadata = {
  title: "VideoGraph",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />

        <link
          rel="stylesheet"
          href="assets/css/bootstrap.min.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="assets/css/font-awesome.min.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="assets/css/elegant-icons.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="assets/css/owl.carousel.min.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="assets/css/magnific-popup.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="assets/css/slicknav.min.css"
          type="text/css"
        />
        <link
          rel="stylesheet"
          href="assets/css/style.css"
          type="text/css"
        ></link>
      </head>

      <body>
        {children}
      </body>
      <Script src="assets/js/jquery-3.3.1.min.js"/>
        <Script src="assets/js/bootstrap.min.js"/>
        <Script src="assets/js/jquery.magnific-popup.min.js"/>
        <Script src="assets/js/mixitup.min.js"/>
        <Script src="assets/js/masonry.pkgd.min.js"/>
        <Script src="assets/js/jquery.slicknav.js"/>
        <Script src="assets/js/owl.carousel.min.js"/>
        <Script src="assets/js/main.js"/>
    </html>
  );
}
